version: "3.9"

services:

  postgresql:
    image: "postgres:14-alpine"
    container_name: postgresql
    volumes:
      - /etc/ipo-ddbb/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ipoDB
      - POSTGRES_USER=ipoUser
      - POSTGRES_PASSWORD=test123@
    networks:
      - ipo-net

  app:
    build: ./app
    container_name: ipo-app
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - ipo-net

networks:
  ipo-net:
    driver: bridge