name: RaspBerryPiWeb
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Intall modules
        run: cd ./app && npm install